### ISSUE TITLE
【バグ】 新規にゲームを始めることができない

### ISSUE THREAD

**Issue by Taro0910** [sikabane-works/bakabakaband#1318]
## 環境

- OS: Windows 版
- バージョン:  3.0.0Alpha22

## バグの詳細
掲題の通りです。
元あるセーブファイルでQy@して新しくゲームを始める、またはメニューから新規を選んでもフリーズし、そもそも遊ぶことができなくなります。

## 再現手順

上記の通り

## 期待される正常な動作
キャラクター作成またはクイックスタートするかどうかの確認画面が出る
## 補足事項
旧バージョンのセーブデータをロードすることは出来ました。

**Comment by Taro0910** [comment]
Alpha23にしたら解決したようです。新規で始めても元からあったセーブファイルを起動しても大丈夫でした。原因不明のままでしたがとりあえずありがとうございます。

**Comment by sikabane-works** [comment]
報告ありがとうございます、閉じます。
