### ISSUE TITLE
アライアンス『GO教』追加

### ISSUE THREAD

**Issue by sikabane-works** [sikabane-works/bakabakaband#1385]
GO is GOD.

**Comment by Thujopsis** [comment]
言語ネタで、GO言語のGofer君とか初期マスコットをネタに入れてもいいかもしれませんなぁ。

**Comment by sikabane-works** [comment]
流石にちょっと風評被害とネタが的外れすぎる気がするねんな……SATSUGAI対象にするのもちと忍びない。

**Comment by Thujopsis** [comment]
なるほどなぁ。　まぁ、それならそれでというところ。
