### ISSUE TITLE
【バグ】 セーブデータをロードするとユニークモンスターが全滅している

### ISSUE THREAD

**Issue by Taro0910** [sikabane-works/bakabakaband#1402]
## 環境

- OS: [Windows 版]
- バージョン: [3.0.0Alpha23]

## バグの詳細
ゲームをセーブして終了してから再び馬鹿馬鹿蛮怒を開き、再開するとユニークモンスターが全て死んだ扱いになります。ウィザードコマンドでも出現させることが出来ず、モンスター情報を見ても全てのユニークが死亡扱いとなっています。

## 再現手順

上記の通り

## 期待される正常な動作
セーブから再開してもユニークモンスターの生存or死亡の状態が保持されている

## 補足事項

バグが発生する前にユニークをいくら倒しても関係なく発生するようです。
また、ユニークモンスターが必ず発生する場所に入るとユニークが正常に登場し、モンスター情報を見ると生存している状態に代わります。（ゴルフィンブールで確認。バグ発生後にオークのキャンプクエストに入るとゴルフィンブールがちゃんといる）

**Comment by sikabane-works** [comment]
ユニーク逝きスギィ！センセンシャル！すぐ直します。
