### ISSUE TITLE
クエストネタ「迫真空手部の興亡」

### ISSUE THREAD

**Issue by RL-Nadir** [sikabane-works/bakabakaband#1614]
ほら、見ろよ見ろよ

（GitHubの仕組みはよくわからないので、クエストデータのテキストファイルを添付しておきますね
[q0clone0.txt](https://github.com/sikabane-works/bakabakaband/files/7776564/q0clone0.txt)
）

**Comment by sikabane-works** [comment]
アリガトナス。咥えいれてみます。

**Comment by sikabane-works** [comment]
ちゃんと動作するようにチェックして修正のうえ再マージ
