### ISSUE TITLE
店主のシャッフル処理廃止

### ISSUE THREAD

**Issue by sikabane-works** [sikabane-works/bakabakaband#1661]
あまり起きることがない、わざわざ執拗に起こそうとしてもメリットが薄い。これからの店舗機能拡張とは余り合わないので、少なくとも馬鹿馬鹿では廃止する。

**Comment by Hourier** [comment]
本家での導入に大賛成です、むしろ前提として本家でやって移植した方が早いまであると思われます
シャッフル条件の1つが「商品を空にする」だったと記憶してますが、狙わないとまず起きない事象であり、起きても新たな商品が並ぶだけの場合もありました
そしてシャッフルさせるメリットは同様にまとものが思いつかなかったです
- 上限金額を変える (最近3万に統一されたのでやるだけ無駄)
- ＠の種族判定と一致させて少し安くする (魅力ペナの重いビルドでもそこまでして安くするか？ というレベル。この機能自体不要かも)
- フレーバー的に色んな店主がいて色々楽しめる (恐らく元々の実装理由、今となっては設計の足枷状態)

**Comment by sikabane-works** [comment]
シャッフルの条件は他にも突然変異の「ランダムなモンスター消滅」を町で起こすと、ランダムに我が家と博物館以外の店主が一人「店の主人が丘に向かって走っている！」というメッセージと共に交代するケースのようです。
具体的メリットは、新しい店主の品はstore_shuffleの後、アーティファクト以外は「売出中」で価格50%OFFで販売されることですね。これも本当に意図的に得るには面倒な変異で起きる隠し効果みたいなもので惜しいと言えば惜しいかもしれませんが、これからの拡張にはやはり微妙かなとも思っています。
これら踏まえてなお変愚でもさっさとやった方がいいなら、変愚にもチケット上げてオミット作業検討しようかなと思います。

**Comment by Hourier** [comment]
確かにそのメッセージは作業中に見た記憶があります
しかし条件の確定までは読み解けませんでした
イースターエッグもいいところですし、消してリファクタリングした後に再実装を検討したとしても遅くはないと思います
他開発者の意見も聞きたいので、本家側のチケットかDiscussionに登録してもらえると助かります
