### ISSUE TITLE
【バグ】辺境の町でレッサー不潔以下略と遭遇しエラー

### ISSUE THREAD

**Issue by meetname** [sikabane-works/bakabakaband#174]
## 環境
- OS: [Windows 版]
- バージョン: [例: 0.0.0Alpha1]
## バグの詳細
辺境の町をうろついてたところ、「レッサー不潔で醜い哀れな身なりのわきめふらつくキチガイ人間」というモンスターに
隣接したところでエラー。
## 期待される正常な動作
エラーが起きないこと。プレイ開始直後なので何が正常な動作なのか分かりません。
## スクリーンショット
![スクリーンショット とり](https://user-images.githubusercontent.com/79730818/113354227-d2174b80-9379-11eb-9eb0-77732ce7bb82.png)
##補足
エラー通知を消したところ、動作再開したのでエラー落ちではない様子。

**Comment by sikabane-works** [comment]
ありがとうございます。旧D'angからの輸入でちょっと癖のあるモンスターなんで気を付けナス！

**Comment by sikabane-works** [comment]
設定ミス修正しました。
