### ISSUE TITLE
【バグ】 アリーナ挑んだらセーブ破損

### ISSUE THREAD

**Issue by meetname** [sikabane-works/bakabakaband#182]
## 環境
- OS: [例: Windows 版]
- バージョン: [例: 0.0.0Alpha0]
## バグの詳細
アリーナ初戦のノボータ・ケシータに挑もうとしたところエラー、のち通知を消すとシャットダウン。
シャットダウン後、該当saveをロードしても読み込み終了直後にシャットダウンしてしまう。
## 再現手順
アリーナに挑むこと？
## 期待される正常な動作
アリーナ戦が始まりエラーが起きないこと。
## スクリーンショット
![スクリーンショット  とり](https://user-images.githubusercontent.com/79730818/113448346-9bebd180-9436-11eb-954e-11090ffec166.png)
## 補足事項
https://www.axfc.net/u/4035148.dat
役に立つか不明ですがロードできなくなったsaveを添付します。
上記スクショの状況ですが下水道クエストクリア直後でした。

**Comment by sikabane-works** [comment]
ありがとうございます。こちら本日中に修正試みます。

**Comment by sikabane-works** [comment]
![2021-04-04 (1)](https://user-images.githubusercontent.com/61610939/113500457-101e9600-9559-11eb-9481-650e34eb54ad.png)
マップサイズに関する定数をいじったものを一度暫定的に修正したはずだったのですが、後日あれこれいじっていた際に再発したようです。今回そういう事態にならないように定数をいじり、かつ変愚とはちょっと違うデザインにしてみました。
いただいたセーブデータは本日リリースのバージョンで復帰できると思いますのでしばらくお待ちください。
