### ISSUE TITLE
【バグ】 モンスター仙人で情報を聞くとエラー

### ISSUE THREAD

**Issue by meetname** [sikabane-works/bakabakaband#183]
## 環境
- OS: [例: Windows 版]
- バージョン: [例: 0.0.0Alpha0]
## バグの詳細
モンスター仙人でtシンボルの「種付けおじさん」の思い出を聞いたところエラーを吐きシャットダウン。
セーブはロード可能。
ただし他のtシンボルの思い出を聞いてから再度「種付けおじさん」の思い出を聞くとエラーにならず正常に思い出を聞くことができた。
## 再現手順
不明。
## 期待される正常な動作
エラーを吐かず思い出を聞き出せること。

**Comment by meetname** [comment]
モンスター仙人以外に種付けおじさんをターゲットにして思い出を見てもエラーが発生するようです

**Comment by sikabane-works** [comment]
進化先の指定IDを催眠おじさんにしたつもりが指定が狂っていたようです。報告ありがとうございます。
