### ISSUE TITLE
【バグ】食べ物が食べられない

### ISSUE THREAD

**Issue by meetname** [sikabane-works/bakabakaband#190]
## 環境
- OS: [例: Windows版
- バージョン: [例: 0.0.0Alpha1]
## バグの詳細
きのこ類、食料、エルフの旅糧でも食べるのを躊躇するため食べられない
## 再現手順
スタート直後に雑貨屋で買い食いする。
## 期待される正常な動作
食べられる。

**Comment by sikabane-works** [comment]
#170 と重複した案件だと思われます。

**Comment by sikabane-works** [comment]
[Bakabakaband-0.0.0Alpha1r-jp.zip](https://github.com/sikabane-works/bakabakaband/files/6253835/Bakabakaband-0.0.0Alpha1r-jp.zip)

本日変愚共々、リリース予定でクロスチェックできないのは不安ですので、もしよろしければ確認していただけると幸いです。

**Comment by meetname** [comment]
alpha1r版では食べられました。ありがとうございます。

**Comment by sikabane-works** [comment]
確認ありがとうございます。チケット閉じます。
