### ISSUE TITLE
【バグ】 目力先輩の思い出

### ISSUE THREAD

**Issue by meetname** [sikabane-works/bakabakaband#211]
## 環境
- OS: [例: Windows 版]
- バージョン: [例: 0.0.0Alpha2]
## バグの詳細

目力先輩の情報をモンスター仙人で尋ねると、打撃が「それの攻撃については何も知らない」と表示される。

## 期待される正常な動作
打撃を持たないモンスターの場合、クイルスルグ等同様「それは物理的な攻撃方法を持たない。」となるはず。

## スクリーンショット
![スクリーンショット 目力トリミング](https://user-images.githubusercontent.com/79730818/113576000-b9e54c00-9659-11eb-8fed-c56dc7efbff4.png)

**Comment by sikabane-works** [comment]
NEVER_BLOW付け忘れてました（小声）

**Comment by sikabane-works** [comment]
終了します。
