### ISSUE TITLE
【バグ】 店の売買金額の上限について

### ISSUE THREAD

**Issue by meetname** [sikabane-works/bakabakaband#212]
## 環境
- OS: [例: Windows 版]
- バージョン: [例: 0.0.0Alpha2]
## バグの詳細
1.店主名右側に表示されている店の売却金額上限を越えた値段でアイテムを売却できる。これは馬鹿馬鹿の新仕様だと思いますが一応。
2.魔法書四冊目一つは10万で売却できますが、10万四冊目を二つ売った場合でも10万金しか得られない。
同様の例として、三冊目(25000金相当)を複数個売った場合でも25000金しか得られない。
## 期待される正常な動作
売却したアイテムの価格×売却した数の売却金額が得られること。
## 補足事項
一個ずつ売れば上記2は回避できる。

**Comment by sikabane-works** [comment]
ああ、店舗の値切り交渉を仮廃止した結果の副作用ですね。こういうとこも直した上で買い取り額も無制限にするか大きく上げたいと思います。

**Comment by sikabane-works** [comment]
まだ値切り/吹っ掛け廃止による問題はいくつかありますがひとまず、売却総額詐欺は直したので本件は解決にします。
