### ISSUE TITLE
「持ち歩けないアイテム」（NEVER_MOVE）を実装する

### ISSUE THREAD

**Issue by sikabane-works** [sikabane-works/bakabakaband#219]
アイテムに床に置かれたまま移動が一切できないアイテムを実装する。回復の泉や、回数制限つきの固定砲、碑文などをこれで表現する。

**Comment by meetname** [comment]
声に出して読みたい名文の碑石が岡山の中央に設置されるのか（期待）

**Comment by sikabane-works** [comment]
後は数々の怪文書や黒塗りの高級車への因果収斂ですな。WEBでネタだしした「冥王の書簡」みたな、ちょっと各原作のネタ要素、二次創作要素も好き勝手足していきます。
