### ISSUE TITLE
もっと危険だったり有用だったりするトラップを増やす

### ISSUE THREAD

**Issue by sikabane-works** [sikabane-works/bakabakaband#229]
深層でもうっかりすると直接ごっそりＨＰを持っていかれたり、炎や氷、ログルスの巻物のような周辺も巻き込むようなトラップなどを考える。

**Comment by sikabane-works** [comment]
テスト。

**Comment by RL-Nadir** [comment]
フロアに影響を及ぼすタイプの罠のバリエーションとして、生成から一定時間経過すると勝手に発動してしまうようなのもあると面白そうだと思いました。
のんびり探索していると、勝手にそこら中糞まみれになっていたり、うま味だけど、すぐにカオス嵐でアイテムが壊されるvaultみたいなのが作れるかも知れません。

**Comment by sikabane-works** [comment]
いいですな。終盤啓蒙し放題の中で悠長に探索していてもいかんようなシステムは高級ドロップ保証も含めて作ってみるといい気がしてきました。一考します。
