### ISSUE TITLE
RaceBlowMethodTypeに「囁く/Whisper」を追加。

### ISSUE THREAD

**Issue by sikabane-works** [sikabane-works/bakabakaband#2432]
Nash Music Library（迫真）

**Comment by RL-Nadir** [comment]
う○ちして☆　も再現できるな

**Comment by sikabane-works** [comment]
![image](https://user-images.githubusercontent.com/61610939/195959715-0eccf4a2-bb37-4af4-b36c-86e98f2cd4a3.png)
ほら！こうだぞ！
