### ISSUE TITLE
【バグ】M（マップ）コマンドで領域外参照

### ISSUE THREAD

**Issue by sikabane-works** [sikabane-works/bakabakaband#303]
詳細確認中。発生はほぼ確実におきる。

**Comment by sikabane-works** [comment]
現状全角表示時のみ発生する模様。マップ圧縮時に反映する座標がtermの範囲を超えてしまうのが原因。変愚では発生していないので、馬鹿馬鹿でマップサイズを変更したのが原因か。

**Comment by sikabane-works** [comment]
横を少し縮小して対応。

**Comment by Hourier** [comment]
以下、関係あるかもしれません
ご参考まで
https://github.com/hengband/hengband/issues/990

**Comment by sikabane-works** [comment]
ありがとうございます。対処療法よりもこっちの修正視野に入れた方がよさげですな。
