### ISSUE TITLE
【バグ】 種族：幽霊が杖・魔法棒・ロッドから魔力を吸収できない

### ISSUE THREAD

**Issue by rkouyou** [sikabane-works/bakabakaband#319]
## 環境

- OS: Windows10 Home [2004]

- バージョン: 0.0.0Alpha4

## バグの詳細

種族：幽霊が杖・魔法棒・ロッドから魔力を吸収できない。

## 再現手順

バグを発生させる手順が分かっていれば記載

1. 杖・魔法棒・ロッドを食べる(E)で選択
2. 「流石に食べるのを躊躇した」として食べられない（魔力吸収できない）

この手順を実行する事でバグを発生させる事ができるセーブファイルがあれば添付

## 期待される正常な動作
魔力吸収してお腹が膨れる。

## スクリーンショット

![202105021945](https://user-images.githubusercontent.com/83537717/116810979-bf16b780-ab81-11eb-8f41-b603eaa80618.png)

## 補足事項

変愚蛮怒3.0.0Alpha20では、正常に動作。

**Comment by sikabane-works** [comment]
了解です。報告ありがとうございます。

**Comment by sikabane-works** [comment]
ひとまず直しました。なんかまだ問題がないかは次リリースまでに引き続きチェックします。

**Comment by sikabane-works** [comment]
またチェックしましたが、一応直ったようなので閉じます。
