### ISSUE TITLE
【バグ】 *破壊*で時空崩壊度が減少する

### ISSUE THREAD

**Issue by rurero2** [sikabane-works/bakabakaband#3779]
## 環境

- win10
-alpha37,alpha45

## バグの詳細

*破壊*で時空崩壊度が減少する

## 再現手順

適当な職で*破壊*の杖を振ると時空崩壊度が減少する

## 期待される正常な動作

時空崩壊度が増える

**Comment by sikabane-works** [comment]
確認しました。ある程度時空崩壊が進むと逆に回復するようです。

**Comment by sikabane-works** [comment]
クッソ単調なミスであることが判明しました。多分次回以降直っとるはずです。
