### ISSUE TITLE
不思議のダンジョンシリーズの印システムと壺アイテムの実装

### ISSUE THREAD

**Issue by KeitoTobi1** [sikabane-works/bakabakaband#378]
印システムは、不思議のダンジョンシリーズにあった「合成の壺」などといった方法でアイテム同士を合成させて一方のアイテムにもう一方のアイテムが持つ印（＝FF7のマテリア）をつけるシステム。
シレン２以降では、つけられる印の数に限度がある。
また、「武器強化の巻物」や「防具強化の巻物」に関しても不思議のダンジョンシリーズに倣う物を実装してほしい。
壺システム（世界観等に合わせて変更してもいい）は、アイテムの所有数を増やしたり、中に入っているアイテムや@に効果を与えるもの。

**Comment by KeitoTobi1** [comment]
ディアボロの大冒険の装備ディスクも実装できれば実装してほしい。

**Comment by sikabane-works** [comment]
壺、装備強化、ディスクは、できれば個別に分けてください。武器防具の巻物を不思議のダンジョンシリーズと仕様がどう違うのか、また敢えてそちらに移行すべき理由などお願いします。

**Comment by KeitoTobi1** [comment]
分割に伴いClose。
