### ISSUE TITLE
【バグ】 未知の地形というアイテムが生成される

### ISSUE THREAD

**Issue by rurero2** [sikabane-works/bakabakaband#3780]
## 環境

- windows10
- 0.0.0alpha45

## バグの詳細

モンスターのドロップで未知の地形(解除済)というアイテムが生成されることがある

## 再現手順

不明。アイテムタイプは大きな箱などと同じ？トラップがついていて解除したような気もするが不明
セーブファイルなし。

## 期待される正常な動作

生成されない

## スクリーンショット

なし
  [我が家のアイテム]

 ( 1 ページ )
a) 3冊の 自然の魔法書[自然の恵み] {@mc!k}
b) 未知の地形(解除済)
c) 腕力復活のキノコ
d) 全復活のキノコ

のようになった

## 補足事項

補足事項があれば記載

**Comment by sikabane-works** [comment]
修正かけました。報告ありがとうございました。
