### ISSUE TITLE
風来のシレンシリーズのゲイズの実装

### ISSUE THREAD

**Issue by KeitoTobi1** [sikabane-works/bakabakaband#379]
ゲイズについて知らない人は[SFC版の攻略記事](http://twist.jpn.org/sfcsiren/index.php?%E3%82%B2%E3%82%A4%E3%82%BA)があるのでこれを見てほしい。
あと、それに伴う「催眠」状態の実装。

**Comment by sikabane-works** [comment]
いわゆる精神支配系でNPCがプレイヤーを操ったり逆にする機能というのは面白いので実装検討してもいいですが、既存の仕様上膨大な追加実装が要ります。気長にお願いします。
