### ISSUE TITLE
憑依（何らかの自己犠牲行為）により他モンスターを強化する能力の実装

### ISSUE THREAD

**Issue by KeitoTobi1** [sikabane-works/bakabakaband#380]
ぼうれい武者が憑依したときの挙動も考えてほしい。

**Comment by sikabane-works** [comment]
出来れば効果などは既存の変愚/馬鹿馬鹿の実装を踏まえて具体的にお願いします。他ゲームの知識を他人が知っている前提で話されても応じかねます。
