### ISSUE TITLE
モンスター変身システムの実装

### ISSUE THREAD

**Issue by KeitoTobi1** [sikabane-works/bakabakaband#381]
変異ではなく直接モンスターに変身するニュアンスのやつ。
（Nethackにはすでに存在するようだ）
肉系のアイテムはシレンとGB版SaGaシリーズを足して二で割るイメージで。
モンスターに変身するアイテムである肉を生み出す『ブフーの包丁』の実装を検討すべき。
あと、ついでに一定ターンで強制的に変身する種族の実装。

**Comment by sikabane-works** [comment]
Xangbandの変身術師が該当すると思うので逆輸入など検討します。ただD'angband的拡張を取るとなるともう少し勝手が変わり時間がかかると思うので気長にどうぞ。
