### ISSUE TITLE
罠のアイテム化

### ISSUE THREAD

**Issue by KeitoTobi1** [sikabane-works/bakabakaband#382]
何故か罠を拾えたり、罠にかからなかったりするアイテムの実装。
アイデアの元ネタは風来のシレンの『罠師の腕輪』。

**Comment by sikabane-works** [comment]
罠のアイテム化と持ち運び、自分で設置などの能動的利用は旧D'angでも使いたかったアイデアなので採用します。前提となる実装は多いので気長にどうぞ。
