### ISSUE TITLE
不思議のダンジョンの武器強化システムを実装

### ISSUE THREAD

**Issue by KeitoTobi1** [sikabane-works/bakabakaband#383]
「アイテム強化の巻物」（シレンで言う武器強化の巻物と盾強化の巻物を統合したもの）で武器や防具といったアイテムを強化できる。
武器は修正値+1につき重量に関係なく攻撃回数が1～3回増え、
防具は修正値+1につきACが2～4増える。
武器には強化限度という概念があり全く同じ武器を使えば使うほど強化限度が増えていく。（減っていく場合もあり）

**Comment by sikabane-works** [comment]
これは普通にほぼ類似のものが昔から実装されていますが、それを拡張したいのならもう少し具体的にお願いします。

**Comment by KeitoTobi1** [comment]
変愚蛮怒に不思議のダンジョンシリーズの修正値システムを導入する。
それによって、使えない武器とかの性能を強化できる。
それに伴う修正値システム系のアイテムの追加を要望。
