### ISSUE TITLE
不思議のダンジョンにあった壺システムの実装

### ISSUE THREAD

**Issue by KeitoTobi1** [sikabane-works/bakabakaband#390]
#378 から分離。
「壺」はアイテムを保存したり、アイテムを合成ないしは強化させたりできる便利アイテム。
「保存の壺」を使うことでアイテムを持てる重量に関係なくアイテムを保存できる容量を増やせる。
また、「壺」によっては押すと効果を発揮するものも存在する。
「壺」の仕様に関しては「覗く」コマンドで覗いて、「なにか」が入っていたら「押す」コマンドが、何も入っていなかったら「アイテムを入れる」コマンドが使える。
「壺から取り出す」コマンドを使って入れたアイテムを取り出せたらそれは「保存の壺」である。
アイテムに関連する「壺」は壁にぶつけて壊さないと取り出せないので注意。

**Comment by sikabane-works** [comment]
壺のルールはある程度見聞きしていたことはありますが、変愚でどう運用すべきかはもう少し考えようと思います。少なくとも余分にアイテムを持てるようにする、という観点ならば勝手版のお燐など前例がない訳ではないので前向きに考えます。
