### ISSUE TITLE
ダンジョン内のお店のルールを変更

### ISSUE THREAD

**Issue by KeitoTobi1** [sikabane-works/bakabakaband#407]
ダンジョン内のお店のルールは不思議のダンジョンシリーズに準拠に変更。
そして、生成頻度が増加されイークの洞窟でも生成されるように。

**Comment by sikabane-works** [comment]
店舗の拡張については別Issueで考えています。そちらと包括して行いますので重複扱いします。

**Comment by sikabane-works** [comment]
#9
