### ISSUE TITLE
新しいトラップ作成時のエンバグ

### ISSUE THREAD

**Issue by sikabane-works** [sikabane-works/bakabakaband#425]
ネタとして仕込まれた可能性があると思い、こちらで伺います。
「床が行く手を阻んでいる」と表示されて、移動・採掘不可能な「床」地形が発生しました。
スクショの＠の上1マスに発生しています。
これって、そういうネタでしょうか。もしバグでしたら、issueの方にセーブデータも上げるようにします。

![image](https://user-images.githubusercontent.com/79453028/119503364-da05d180-bda5-11eb-8f92-197729dbee1e.png)

_Originally posted by @RL-Nadir in https://github.com/sikabane-works/bakabakaband/discussions/422_

**Comment by RL-Nadir** [comment]
なんとなく、原因に思い当たりがありそうに見えますが、セーブデータも貼っておきますね。
そのままでは怒られたので、zipにしました。パスはありません。

[Nadir.zip](https://github.com/sikabane-works/bakabakaband/files/6546575/Nadir.zip)

**Comment by sikabane-works** [comment]
あざます。

**Comment by sikabane-works** [comment]
単純に乱数範囲が誤っていて、不正な値をとった場合に実質永久壁になっている地形を生成していました。トラップ創造の巻物で不正なトラップが生成されないよう修正しました。報告ありがとうございます。次バージョン移行、万一再発見したらお知らせください。
